In [1]:
from scripts.conf_file_finding import try_find_conf_file

try_find_conf_file()

Local configuration file found !!, no need to run the configuration (unless configuration has changed)

In [2]:
import datajoint as dj
import pandas as pd

import u19_pipeline.imaging_pipeline as ip
import u19_pipeline.utils.tiff_matlab_imaging_utils as tmiu
import u19_pipeline.utils.tiff_utils as tu

/mnt/cup/braininit/Shared/repos/TestU19PipelinePython2/U19-pipeline-python/.venv/lib/python3.13/site-packages/datajoint/plugin.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-05-22 20:26:48,224][INFO]: DataJoint 0.14.6 connected to alvaros@datajoint00.pni.princeton.edu:3306

In [3]:
import importlib

importlib.reload(ip)
importlib.reload(tu)
importlib.reload(tmiu)

In [4]:
behavior = dj.create_virtual_module("behavior", "u19_behavior")

In [5]:
acquired_tiff_keys = ip.AcquiredTiff.fetch("KEY")
acquired_tiff_keys

[{'recording_id': 10},
 {'recording_id': 11},
 {'recording_id': 12},
 {'recording_id': 98},
 {'recording_id': 99},
 {'recording_id': 100},
 {'recording_id': 162},
 {'recording_id': 169},
 {'recording_id': 175},
 {'recording_id': 187},
 {'recording_id': 590},
 {'recording_id': 669},
 {'recording_id': 676},
 {'recording_id': 677},
 {'recording_id': 678},
 {'recording_id': 679},
 {'recording_id': 680},
 {'recording_id': 681},
 {'recording_id': 682},
 {'recording_id': 683},
 {'recording_id': 685},
 {'recording_id': 686},
 {'recording_id': 687},
 {'recording_id': 688}]

In [6]:
imaging_key = dict()
imaging_key["recording_id"] = 684
# imaging_key = acquired_tiff_keys[16].copy()
imaging_key
original_imaging_key = imaging_key.copy()
original_imaging_key

{'recording_id': 684}

In [7]:
acquired_tiff_obj = ip.AcquiredTiff()

In [8]:
acquired_tiff_obj.populate(imaging_key)

Preparing /mnt/cup/braininit/Data/Raw/imaging/efonseca/efonseca_ef512_act132/20260519_g1/05192026

Estimating bleaching......................................................................................................... done after 0.2 min

DuplicateError: ("Duplicate entry '684-1-1' for key 'PRIMARY'", 'To ignore duplicate entries in insert, set skip_duplicates=True')

In [9]:
tiff_data = acquired_tiff_obj.make(imaging_key, test_mode=True)

Preparing /mnt/cup/braininit/Data/Raw/imaging/efonseca/efonseca_ef512_act132/20260519_g1/05192026
Estimating bleaching......................................................................................................... done after 0.2 min

In [10]:
original_imaging_key

{'recording_id': 684}

In [153]:
acquired_tiff_entry = (ip.AcquiredTiff & original_imaging_key).fetch(as_dict=True)
tiff_split_entry = (ip.TiffSplit & original_imaging_key).fetch(as_dict=True)
tiff_split_file_entry = (ip.TiffSplit.File & original_imaging_key).fetch(as_dict=True)

In [154]:
new_acqtiff_rec = pd.DataFrame([tiff_data[0]])
original_acqtiff_rec = pd.DataFrame(acquired_tiff_entry)
original_acqtiff_rec = original_acqtiff_rec[new_acqtiff_rec.columns]
pd.concat([original_acqtiff_rec, new_acqtiff_rec]).T

,0,0
recording_id,683,683
file_name_base,efonseca/efonseca_ef932_act131/20260518_g1/051...,/efonseca/efonseca_ef932_act131/20260518_g1/05...
scan_width,512,512
scan_height,300,300
acq_time,2026-05-18 00:00:00,2026-05-18 14:59:49
n_depths,0,0
scan_depths,[[-1.0]],-1
frame_rate,10.0454,10.0454
inter_fov_lag_sec,0.001,0.001
frame_ts_sec,"[[0.0], [0.01991578], [0.03983153], [0.0597473...","[0.0, 0.01991578, 0.03983153, 0.05974734, 0.07..."
power_percent,45.0,45.0
channels,[[1.0]],1
cfg_filename,'C:\PNI182_volumetric.cfg,'C:\PNI182_volumetric.cfg
usr_filename,'C:\PNI182_volumetric.usr,'C:\PNI182_volumetric.usr
fast_z_lag,0.0,0.0
fast_z_flyback_time,0.0,0.0
line_period,0.000063,0.000063
scan_frame_period,0.01991,0.01991
scan_volume_rate,10.0454,10.0454
flyback_time_per_frame,0.001,0.001
flyto_time_per_scan_field,0.001,0.001
fov_corner_points,"[[-204.75, -315.0], [204.75, -315.0], [204.75,...","[[-204.75, -315.0], [204.75, -315.0], [204.75,..."
nfovs,1,1
nframes,183931,183931
nframes_good,183931,183931
last_good_file,92,92

In [11]:
new_tiffsplit_rec = pd.DataFrame([tiff_data[1]])
new_tiffsplit_rec.T

                                                                         0
recording_id                                                           684
tiff_split                                                               1
tiff_split_directory     efonseca/efonseca_ef512_act132/20260519_g1/051...
fov_depth                                                                0
fov_center_xy                                                            0
fov_size_xy                                                              0
fov_rotation_degrees                                                     0
fov_pixel_resolution_xy                                                  0
fov_discrete_plane_mode                                                  0
power_percent                                                         45.0

In [13]:
pd.DataFrame(tiff_split_entry).T

NameError: name 'tiff_split_entry' is not defined

In [157]:
pd.DataFrame(tiff_split_file_entry)

,recording_id,tiff_split,file_number,tiff_split_filename,file_frame_range
0,683,1,1,ef932_act131_ppc_05182026b_00003_00001.tif,"[[1.0, 2000.0]]"
1,683,1,2,ef932_act131_ppc_05182026b_00003_00002.tif,"[[2001.0, 4000.0]]"
2,683,1,3,ef932_act131_ppc_05182026b_00003_00003.tif,"[[4001.0, 6000.0]]"
3,683,1,4,ef932_act131_ppc_05182026b_00003_00004.tif,"[[6001.0, 8000.0]]"
4,683,1,5,ef932_act131_ppc_05182026b_00003_00005.tif,"[[8001.0, 10000.0]]"
...,...,...,...,...,...
87,683,1,88,ef932_act131_ppc_05182026b_00003_00088.tif,"[[174001.0, 176000.0]]"
88,683,1,89,ef932_act131_ppc_05182026b_00003_00089.tif,"[[176001.0, 178000.0]]"
89,683,1,90,ef932_act131_ppc_05182026b_00003_00090.tif,"[[178001.0, 180000.0]]"
90,683,1,91,ef932_act131_ppc_05182026b_00003_00091.tif,"[[180001.0, 182000.0]]"
91,683,1,92,ef932_act131_ppc_05182026b_00003_00092.tif,"[[182001.0, 183931.0]]"

In [12]:
pd.DataFrame(tiff_data[2])

,recording_id,tiff_split,file_number,tiff_split_filename,file_frame_range
0,684,1,1,ef512_act132_ppc_05192026_00001_00001.tif,"[1, 2000]"
1,684,1,2,ef512_act132_ppc_05192026_00001_00002.tif,"[2001, 4000]"
2,684,1,3,ef512_act132_ppc_05192026_00001_00003.tif,"[4001, 6000]"
3,684,1,4,ef512_act132_ppc_05192026_00001_00004.tif,"[6001, 8000]"
4,684,1,5,ef512_act132_ppc_05192026_00001_00005.tif,"[8001, 10000]"
...,...,...,...,...,...
97,684,1,98,ef512_act132_ppc_05192026_00001_00098.tif,"[194001, 196000]"
98,684,1,99,ef512_act132_ppc_05192026_00001_00099.tif,"[196001, 197017]"
99,684,1,1,ef512_act132_ppc_05192026_00002_00001.tif,"[197018, 199017]"
100,684,1,2,ef512_act132_ppc_05192026_00002_00002.tif,"[199018, 201017]"
101,684,1,3,ef512_act132_ppc_05192026_00002_00003.tif,"[201018, 202700]"