# Create weighingGUI Spreadsheet daily

In [1]:
from scripts.conf_file_finding import try_find_conf_file

try_find_conf_file()

Local configuration file found !!, no need to run the configuration (unless configuration has changed)

In [2]:
import base64
import datetime
import pathlib
import shutil
import time

import datajoint as dj
import numpy as np
import openpyxl
import pandas as pd
from openpyxl.drawing.image import Image
from openpyxl.utils.dataframe import dataframe_to_rows

time.sleep(1)

import u19_pipeline.acquisition as acquisition
import u19_pipeline.alert_system.water_weigh_alert.water_weigh_alert as wwa
import u19_pipeline.behavior as behavior
import u19_pipeline.lab as lab
import u19_pipeline.scheduler as scheduler
import u19_pipeline.subject as subject

DJ_CUSTOM_VARIABLES_FILENAME = "DJCustomVariables.csv"
SLACK_WEBHOOK_FILENAME = "SlackChannels.csv"
USER_SLACK_FILENAME = "UserSlack.csv"
RIG_STATUS_FILENAME = "RigStatusTable.csv"
DAY_SCHEDULE_FILENAME = "ScheduleDay.csv"
PAST_SESSION_PERFORMANCE_FILENAME = "PastSessions.csv"
SUBJECT_MOTOR_POSITION_FILENAME = "SubjectMotorPosition.csv"

WEIGHING_GUI_REPLACEMENT_SPREADHSHEET_FILENAME_TEMPLATE = (
    "Weighing_GUI_Replacement_SpreadSheet_Template.xlsx"
)
WEIGHING_GUI_REPLACEMENT_SPREADHSHEET_FILENAME = (
    "Weighing_GUI_Replacement_SpreadSheet.xlsx"
)


MAX_SESSIONS_HISTORY = 75

/mnt/cup/braininit/Shared/repos/TestU19PipelinePython2/U19-pipeline-python/.venv/lib/python3.13/site-packages/datajoint/plugin.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-05-18 16:26:35,350][INFO]: DataJoint 0.14.6 connected to alvaros@datajoint00.pni.princeton.edu:3306

In [3]:
def cast_choice(choice_array):

    new_array = choice_array[0].copy()
    new_array[new_array > 2] = 127

    new_array = np.array(new_array, dtype=np.uint8)

    return new_array

In [4]:
def encode_webhook(webhook):

    return (base64.b64encode(webhook.encode("utf-8"))).decode("utf-8")

In [5]:
conf = dj.config

nodb_virmen_backup_dir = pathlib.Path(
    pathlib.Path(conf["custom"]["root_data_dir"][0]).parent.parent,
    "Shared",
    "NoDBVirmenBackup",
)

DJ_CUSTOM_VARIABLES_FILENAME = pathlib.Path(
    nodb_virmen_backup_dir, DJ_CUSTOM_VARIABLES_FILENAME
).as_posix()
SLACK_WEBHOOK_FILENAME = pathlib.Path(
    nodb_virmen_backup_dir, SLACK_WEBHOOK_FILENAME
).as_posix()
USER_SLACK_FILENAME = pathlib.Path(
    nodb_virmen_backup_dir, USER_SLACK_FILENAME
).as_posix()
RIG_STATUS_FILENAME = pathlib.Path(
    nodb_virmen_backup_dir, RIG_STATUS_FILENAME
).as_posix()
DAY_SCHEDULE_FILENAME = pathlib.Path(
    nodb_virmen_backup_dir, DAY_SCHEDULE_FILENAME
).as_posix()
PAST_SESSION_PERFORMANCE_FILENAME = pathlib.Path(
    nodb_virmen_backup_dir, PAST_SESSION_PERFORMANCE_FILENAME
).as_posix()
SUBJECT_MOTOR_POSITION_FILENAME = pathlib.Path(
    nodb_virmen_backup_dir, SUBJECT_MOTOR_POSITION_FILENAME
).as_posix()

WEIGHING_GUI_REPLACEMENT_SPREADHSHEET_FILENAME = pathlib.Path(
    nodb_virmen_backup_dir, WEIGHING_GUI_REPLACEMENT_SPREADHSHEET_FILENAME
).as_posix()

WEIGHING_GUI_REPLACEMENT_SPREADHSHEET_FILENAME_TEMPLATE = pathlib.Path(
    nodb_virmen_backup_dir, WEIGHING_GUI_REPLACEMENT_SPREADHSHEET_FILENAME_TEMPLATE
).as_posix()

In [6]:
pd.DataFrame(lab.DjCustomVariables.fetch(as_dict=True)).to_csv(
    DJ_CUSTOM_VARIABLES_FILENAME
)

In [7]:
slack_webhooks = pd.DataFrame(lab.SlackWebhooks.fetch(as_dict=True))
slack_webhooks["webhook_url"] = slack_webhooks["webhook_url"].astype(str)

slack_webhooks["webhook_url"] = slack_webhooks["webhook_url"].apply(encode_webhook)
slack_webhooks.to_csv(SLACK_WEBHOOK_FILENAME, index=False)

In [8]:
user_data = pd.DataFrame(
    lab.User.fetch(
        "user_id", "slack", "tech_responsibility", "slack_webhook", as_dict=True
    )
)
user_data["slack_webhook"] = user_data["slack_webhook"].astype(str)
user_data["slack_webhook"] = user_data["slack_webhook"].fillna("")

user_data["slack_webhook"] = user_data["slack_webhook"].apply(encode_webhook)
user_data.to_csv(USER_SLACK_FILENAME, index=False)

In [9]:
df_rig_status = pd.DataFrame(
    scheduler.RigStatus.fetch(
        "location", "input_output_name", "current_status", as_dict=True
    )
)
df_rig_status.to_csv(RIG_STATUS_FILENAME, index=False)

In [10]:
schedule_query = dict()
schedule_query["date"] = datetime.date.today()

subject_query = "subject_fullname is not null"

day_schedule = pd.DataFrame(
    (
        scheduler.Schedule
        * scheduler.TrainingProfile
        * subject.Subject.proj(subject_user_id="user_id")
        & schedule_query
        & subject_query
    ).fetch(as_dict=True)
)
day_schedule = day_schedule.drop(columns="user_id")
day_schedule = day_schedule.rename(columns={"subject_user_id": "user_id"})


day_schedule.to_csv(DAY_SCHEDULE_FILENAME, index=False)
day_schedule

,date,location,timeslot,training_profile_id,subject_fullname,recording_profile_id,input_output_profile_id,experimenters_instructions,level,sublevel,date_created,date_last_used,training_profile_name,training_profile_description,training_profile_variables,deprecated,user_id
0,2026-04-30,165A-miniVR-T-1,2,154,efonseca_ef717_sta531,1,5,Do NOT change DV (up-down) coordinates.,0,0,2026-01-21,2026-01-21,LSTT_Stationary_TrainingProfile,,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0], [...",0,efonseca
1,2026-04-30,165A-miniVR-T-1,3,145,efonseca_ef730_act134,1,5,Do not change DV coordinates,0,0,2025-05-06,2025-05-06,LSTT_Levels_GradualParamChange_EFv2,This is an autogenerated Profile for LSTT_Leve...,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,efonseca
2,2026-04-30,165A-miniVR-T-2,2,154,efonseca_ef718_sta532,1,5,Do NOT change DV (up-down) coordinates. Thanks!,0,0,2026-01-21,2026-01-21,LSTT_Stationary_TrainingProfile,,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0], [...",0,efonseca
3,2026-04-30,165A-miniVR-T-2,3,152,efonseca_ef722_pas332,1,5,Do not change DV coordinates. Thanks!,0,0,2025-10-09,2025-10-09,LSTT_Passive_TrainingProfile,,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0], [...",0,efonseca
4,2026-04-30,165A-miniVR-T-3,1,145,efonseca_ef505_act133,1,5,Do not change DV (up-down) coordinates. Thanks,0,0,2025-05-06,2025-05-06,LSTT_Levels_GradualParamChange_EFv2,This is an autogenerated Profile for LSTT_Leve...,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,efonseca
5,2026-04-30,165A-miniVR-T-3,2,152,efonseca_ef721_pas331,1,5,Do NOT change DV (up-down) coordinates. Thanks!,0,0,2025-10-09,2025-10-09,LSTT_Passive_TrainingProfile,,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0], [...",0,efonseca
6,2026-04-30,165A-miniVR-T-4,1,155,jounhong_DRD1cre_983,1,1,,0,0,2026-02-03,2026-02-03,Standard_TowersTask,Towers Task,"{""pretraining_instructions"": null, ""posttraini...",0,jounhong
7,2026-04-30,165A-miniVR-T-4,2,155,jounhong_DRD1cre_984,1,1,,0,0,2026-02-03,2026-02-03,Standard_TowersTask,Towers Task,"{""pretraining_instructions"": null, ""posttraini...",0,jounhong
8,2026-04-30,165A-miniVR-T-4,3,155,jounhong_DRD1cre_988,1,1,,0,0,2026-02-03,2026-02-03,Standard_TowersTask,Towers Task,"{""pretraining_instructions"": null, ""posttraini...",0,jounhong
9,2026-04-30,165A-miniVR-T-4,4,155,jounhong_A2Acre_956,1,1,,0,0,2026-02-03,2026-02-03,Standard_TowersTask,Towers Task,"{""pretraining_instructions"": null, ""posttraini...",0,jounhong
10,2026-04-30,165A-miniVR-T-4,5,155,jounhong_A2Acre_965,1,1,,0,0,2026-02-03,2026-02-03,Standard_TowersTask,Towers Task,"{""pretraining_instructions"": null, ""posttraini...",0,jounhong
11,2026-04-30,165A-miniVR-T-4,6,155,jounhong_A2Acre_957,1,1,,0,0,2026-02-03,2026-02-03,Standard_TowersTask,Towers Task,"{""pretraining_instructions"": null, ""posttraini...",0,jounhong
12,2026-04-30,165A-miniVR-T-5,1,131,jk8386_jk114,1,2,LASER ON\nmake sure cables are attached\nlsrep...,0,0,2025-04-14,2025-04-14,jesse_chronic_spatfreq_prot,Jesse's spatfreq task for optogenetics across ...,"{""rewardFactor"": [[1.0, 1.0, 1.0, 1.0, 1.0, 1....",0,jk8386
13,2026-04-30,165A-miniVR-T-5,2,131,jk8386_jk115,1,2,LASER ON\nmake sure cables are attached\nlsrep...,0,0,2025-04-14,2025-04-14,jesse_chronic_spatfreq_prot,Jesse's spatfreq task for optogenetics across ...,"{""rewardFactor"": [[1.0, 1.0, 1.0, 1.0, 1.0, 1....",0,jk8386
14,2026-04-30,165A-miniVR-T-5,3,131,jk8386_jk116,1,2,LASER ON\nmake sure cables are attached\nlsrep...,0,0,2025-04-14,2025-04-14,jesse_chronic_spatfreq_prot,Jesse's spatfreq task for optogenetics across ...,"{""rewardFactor"": [[1.0, 1.0, 1.0, 1.0, 1.0, 1....",0,jk8386
15,2026-04-30,165A-miniVR-T-5,4,131,jk8386_jk119,1,2,LASER ON\nmake sure cables are attached\nlsrep...,0,0,2025-04-14,2025-04-14,jesse_chronic_spatfreq_prot,Jesse's spatfreq task for optogenetics across ...,"{""rewardFactor"": [[1.0, 1.0, 1.0, 1.0, 1.0, 1....",0,jk8386
16,2026-04-30,165A-miniVR-T-5,5,131,jk8386_jk112,1,2,"LASER ON\ndoric file: ""...triggered...50hz...""...",0,0,2025-04-14,2025-04-14,jesse_chronic_spatfreq_prot,Jesse's spatfreq task for optogenetics across ...,"{""rewardFactor"": [[1.0, 1.0, 1.0, 1.0, 1.0, 1....",0,jk8386
17,2026-04-30,165A-miniVR-T-5,6,131,jk8386_jk113,1,2,"LASER ON\ndoric file: ""...triggered...50hz...""...",0,0,2025-04-14,2025-04-14,jesse_chronic_spatfreq_prot,Jesse's spatfreq task for optogenetics across ...,"{""rewardFactor"": [[1.0, 1.0, 1.0, 1.0, 1.0, 1....",0,jk8386
18,2026-04-30,165A-miniVR-T-6,1,142,jjulian_JJ180,1,1,"4/9/26 first day, habituate to ball then run o...",0,0,2025-04-15,2025-04-15,jesse_towers_EC,basic towers task for jesse/josh/jorge entorhi...,"{""pretraining_instructions"": null, ""posttraini...",0,jjulian
19,2026-04-30,165A-miniVR-T-6,2,142,jjulian_JJ181,1,1,"4/9/26 first day, habituate to ball then run o...",0,0,2025-04-15,2025-04-15,jesse_towers_EC,basic towers task for jesse/josh/jorge entorhi...,"{""pretraining_instructions"": null, ""posttraini...",0,jjulian
20,2026-04-30,165A-miniVR-T-6,3,142,jk8386_jk117,1,1,,0,0,2025-04-15,2025-04-15,jesse_towers_EC,basic towers task for jesse/josh/jorge entorhi...,"{""pretraining_instructions"": null, ""posttraini...",0,jk8386
21,2026-04-30,165A-miniVR-T-6,4,142,jk8386_jk118,1,1,,0,0,2025-04-15,2025-04-15,jesse_towers_EC,basic towers task for jesse/josh/jorge entorhi...,"{""pretraining_instructions"": null, ""posttraini...",0,jk8386
22,2026-04-30,165A-miniVR-T-6,5,142,jk8386_jk120,1,1,,0,0,2025-04-15,2025-04-15,jesse_towers_EC,basic towers task for jesse/josh/jorge entorhi...,"{""pretraining_instructions"": null, ""posttraini...",0,jk8386
23,2026-04-30,165A-miniVR-T-6,6,155,jounhong_A2Acre_966,1,1,,0,0,2026-02-03,2026-02-03,Standard_TowersTask,Towers Task,"{""pretraining_instructions"": null, ""posttraini...",0,jounhong
24,2026-04-30,165I-Rig1-T,1,150,jeremyjc_j100,1,1,2 washers; barriers,0,0,2025-06-23,2025-06-23,doorstop_protocol_bigVR,Aspect ratio-corrected doorstop environment fo...,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,jeremyjc
25,2026-04-30,165I-Rig1-T,3,150,jeremyjc_j109,1,1,1 washer; barriers,0,0,2025-06-23,2025-06-23,doorstop_protocol_bigVR,Aspect ratio-corrected doorstop environment fo...,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,jeremyjc
26,2026-04-30,165I-Rig1-T,4,150,jeremyjc_j099,1,1,"HYBRID SCHEDULE: train Tuesday, Thursday, Satu...",0,0,2025-06-23,2025-06-23,doorstop_protocol_bigVR,Aspect ratio-corrected doorstop environment fo...,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,jeremyjc
27,2026-04-30,165I-Rig1-T,5,150,jeremyjc_j107,1,1,"HYBRID SCHEDULE: train Tuesday, Thursday, Satu...",0,0,2025-06-23,2025-06-23,doorstop_protocol_bigVR,Aspect ratio-corrected doorstop environment fo...,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,jeremyjc
28,2026-04-30,165I-Rig1-T,8,150,jeremyjc_j111,1,1,1 washer; barriers,0,0,2025-06-23,2025-06-23,doorstop_protocol_bigVR,Aspect ratio-corrected doorstop environment fo...,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,jeremyjc
29,2026-04-30,165I-Rig2-T,1,80,jyanar_ya072,1,1,,0,0,2025-02-18,2025-02-18,pwm_jessejorge_v2_moon,This is an autogenerated Profile for pwm_jesse...,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,jyanar
30,2026-04-30,165I-Rig2-T,2,80,jyanar_ya073,1,1,,0,0,2025-02-18,2025-02-18,pwm_jessejorge_v2_moon,This is an autogenerated Profile for pwm_jesse...,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,jyanar
31,2026-04-30,165I-Rig2-T,4,131,jk8386_jk123,1,2,LASER ON\nmake sure cables are attached\nlsrep...,0,0,2025-04-14,2025-04-14,jesse_chronic_spatfreq_prot,Jesse's spatfreq task for optogenetics across ...,"{""rewardFactor"": [[1.0, 1.0, 1.0, 1.0, 1.0, 1....",0,jk8386
32,2026-04-30,165I-Rig3-T,1,80,jyanar_ya074,1,1,,0,0,2025-02-18,2025-02-18,pwm_jessejorge_v2_moon,This is an autogenerated Profile for pwm_jesse...,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,jyanar
33,2026-04-30,165I-Rig3-T,3,131,jk8386_jk121,1,2,LASER ON\nmake sure cables are attached\nlsrep...,0,0,2025-04-14,2025-04-14,jesse_chronic_spatfreq_prot,Jesse's spatfreq task for optogenetics across ...,"{""rewardFactor"": [[1.0, 1.0, 1.0, 1.0, 1.0, 1....",0,jk8386
34,2026-04-30,165I-Rig3-T,4,131,jk8386_jk122,1,2,LASER ON\nmake sure cables are attached\nlsrep...,0,0,2025-04-14,2025-04-14,jesse_chronic_spatfreq_prot,Jesse's spatfreq task for optogenetics across ...,"{""rewardFactor"": [[1.0, 1.0, 1.0, 1.0, 1.0, 1....",0,jk8386
35,2026-04-30,165I-Rig4-T,1,80,jyanar_ya064,1,1,"Please use caution, implant is delicate.",0,0,2025-02-18,2025-02-18,pwm_jessejorge_v2_moon,This is an autogenerated Profile for pwm_jesse...,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,jyanar
36,2026-04-30,165I-Rig4-T,2,80,jyanar_ya071,1,1,,0,0,2025-02-18,2025-02-18,pwm_jessejorge_v2_moon,This is an autogenerated Profile for pwm_jesse...,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,jyanar
37,2026-04-30,165I-Rig4-T,3,80,jyanar_ya076,1,1,"~~ New mouse ~~\nFor first three days, 25 drop...",0,0,2025-02-18,2025-02-18,pwm_jessejorge_v2_moon,This is an autogenerated Profile for pwm_jesse...,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,jyanar
38,2026-04-30,165I-Rig4-T,4,80,jyanar_ya061,1,1,Please run today.,19,0,2025-02-18,2025-02-18,pwm_jessejorge_v2_moon,This is an autogenerated Profile for pwm_jesse...,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,jyanar
39,2026-04-30,165I-Rig4-T,5,80,jyanar_ya070,1,1,,19,0,2025-02-18,2025-02-18,pwm_jessejorge_v2_moon,This is an autogenerated Profile for pwm_jesse...,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,jyanar
40,2026-04-30,165I-Rig4-T,6,80,jyanar_ya068,1,1,~~ Do not run ~~\nJorge will train/record.,14,0,2025-02-18,2025-02-18,pwm_jessejorge_v2_moon,This is an autogenerated Profile for pwm_jesse...,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,jyanar
41,2026-04-30,182-Imaging-Rig1,1,157,efonseca_ef512_act132,1,9,"Do not modify DV coordinates, unless too obvio...",0,0,2026-04-17,2026-04-17,LSTT_Active_Imaging,,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,efonseca
42,2026-04-30,182-Imaging-Rig1,2,157,efonseca_ef932_act131,1,9,"Do not modify DV coordinates, unless too obvio...",0,0,2026-04-17,2026-04-17,LSTT_Active_Imaging,,"{""rewardFactor"": [[2.0, 1.5, 1.2, 1.0, 1.0, 1....",0,efonseca

In [ ]:
# shcedule = pd.read_csv(DAY_SCHEDULE_FILENAME)
# shcedule = shcedule.loc[:,['date', 'location','timeslot','subject_fullname','training_profile_id','recording_profile_id','input_output_profile_id','experimenters_instructions']]
# shcedule.loc[shcedule['experimenters_instructions'].isna(),'experimenters_instructions'] = ''
# shcedule
# list_of_dicts = shcedule.to_dict(orient='records')
# scheduler.Schedule.insert(list_of_dicts)

In [11]:
all_subjects_schedule = "', '".join(day_schedule["subject_fullname"])
all_subjects_schedule = "subject_fullname in ('" + all_subjects_schedule + "')"
all_subjects_schedule

"subject_fullname in ('efonseca_ef717_sta531', 'efonseca_ef730_act134', 'efonseca_ef718_sta532', 'efonseca_ef722_pas332', 'efonseca_ef505_act133', 'efonseca_ef721_pas331', 'jounhong_DRD1cre_983', 'jounhong_DRD1cre_984', 'jounhong_DRD1cre_988', 'jounhong_A2Acre_956', 'jounhong_A2Acre_965', 'jounhong_A2Acre_957', 'jk8386_jk114', 'jk8386_jk115', 'jk8386_jk116', 'jk8386_jk119', 'jk8386_jk112', 'jk8386_jk113', 'jjulian_JJ180', 'jjulian_JJ181', 'jk8386_jk117', 'jk8386_jk118', 'jk8386_jk120', 'jounhong_A2Acre_966', 'jeremyjc_j100', 'jeremyjc_j109', 'jeremyjc_j099', 'jeremyjc_j107', 'jeremyjc_j111', 'jyanar_ya072', 'jyanar_ya073', 'jk8386_jk123', 'jyanar_ya074', 'jk8386_jk121', 'jk8386_jk122', 'jyanar_ya064', 'jyanar_ya071', 'jyanar_ya076', 'jyanar_ya061', 'jyanar_ya070', 'jyanar_ya068', 'efonseca_ef512_act132', 'efonseca_ef932_act131')"

In [13]:
sp = pd.DataFrame(
    (subject.HeadMotorPosition & all_subjects_schedule).fetch(as_dict=True)
)

sp.to_csv(SUBJECT_MOTOR_POSITION_FILENAME, index=False)
sp

,subject_fullname,location,ml_position,ap_position,dv_position
0,efonseca_ef505_act133,165A-miniVR-T-3,11.0371,5.32400,6.944770
1,efonseca_ef512_act132,165A-miniVR-T-2,15.9369,15.55730,11.342400
2,efonseca_ef512_act132,182-Imaging-Rig1,14.3208,7.82764,20.000000
3,efonseca_ef717_sta531,165A-miniVR-T-1,14.0443,17.08830,6.500650
4,efonseca_ef718_sta532,165A-miniVR-T-2,16.1466,16.06220,9.465060
5,efonseca_ef721_pas331,165A-miniVR-T-3,11.1176,5.25780,9.407870
6,efonseca_ef722_pas332,165A-miniVR-T-1,18.9131,17.19540,9.360790
7,efonseca_ef722_pas332,165A-miniVR-T-2,16.1466,16.26220,9.465060
8,efonseca_ef722_pas332,165A-miniVR-T-3,10.3716,6.05716,8.827980
9,efonseca_ef730_act134,165A-miniVR-T-1,14.3734,16.63590,7.125800
10,efonseca_ef932_act131,165A-miniVR-T-1,16.3977,16.78830,6.900650
11,efonseca_ef932_act131,165A-miniVR-T-2,16.1327,15.55180,10.954500
12,efonseca_ef932_act131,182-Imaging-Rig1,13.5234,8.28351,20.000000
13,jjulian_JJ180,165A-miniVR-T-6,12.8572,10.75050,8.980620
14,jjulian_JJ181,165A-miniVR-T-6,12.4572,8.97974,8.580620
15,jk8386_jk112,165A-miniVR-T-5,12.7165,4.86137,0.799838
16,jk8386_jk113,165A-miniVR-T-5,12.3165,5.66137,1.999850
17,jk8386_jk114,165A-miniVR-T-5,14.0162,6.23126,2.253950
18,jk8386_jk115,165A-miniVR-T-5,12.4927,5.70217,2.799850
19,jk8386_jk116,165A-miniVR-T-5,11.7165,5.66137,1.999850
20,jk8386_jk117,165A-miniVR-T-6,13.4572,11.55050,7.180610
21,jk8386_jk118,165A-miniVR-T-6,12.5156,9.55050,9.780630
22,jk8386_jk119,165A-miniVR-T-5,12.3165,4.46137,1.399840
23,jk8386_jk120,165A-miniVR-T-6,13.2618,9.35050,8.580620
24,jounhong_A2Acre_956,165A-miniVR-T-4,17.6907,9.69769,15.294500
25,jounhong_A2Acre_957,165A-miniVR-T-4,16.9963,10.89770,14.894500
26,jounhong_A2Acre_965,165A-miniVR-T-4,18.4716,12.29770,16.494500
27,jounhong_A2Acre_966,165A-miniVR-T-6,13.3935,8.09592,9.375460
28,jounhong_DRD1cre_983,165A-miniVR-T-4,17.1837,10.89770,13.522400
29,jounhong_DRD1cre_984,165A-miniVR-T-4,18.0797,11.69770,15.674900
30,jounhong_DRD1cre_988,165A-miniVR-T-4,17.3952,12.29770,13.874900

In [135]:
ss = pd.DataFrame(
    (behavior.TowersSession & all_subjects_schedule).fetch(
        "KEY",
        order_by="subject_fullname, session_date desc, session_number desc",
        as_dict=True,
    )
)
ss["session_date"] = ss["session_date"].astype(str)
ss["num_sessions"] = ss.groupby(["subject_fullname"])["subject_fullname"].rank(
    method="first"
)
ss["num_sessions"] = ss["num_sessions"].astype(int)
ss = ss.loc[ss["num_sessions"] <= MAX_SESSIONS_HISTORY, :]

# ss2 = ss.copy()

max_value_indices = ss.groupby("subject_fullname")["num_sessions"].idxmax()
ss = ss.loc[max_value_indices]
ss = ss.reset_index(drop=True)
ss["query"] = (
    "(subject_fullname='"
    + ss["subject_fullname"]
    + "' and session_date >= '"
    + ss["session_date"]
    + "')"
)

block_query = " OR ".join(ss["query"])
ss

,subject_fullname,session_date,session_number,num_sessions,query
0,efonseca_ef505_act133,2026-01-15,0,37,(subject_fullname='efonseca_ef505_act133' and ...
1,efonseca_ef512_act132,2026-01-10,0,43,(subject_fullname='efonseca_ef512_act132' and ...
2,efonseca_ef717_sta531,2026-01-29,2,24,(subject_fullname='efonseca_ef717_sta531' and ...
3,efonseca_ef718_sta532,2026-01-29,1,27,(subject_fullname='efonseca_ef718_sta532' and ...
4,efonseca_ef721_pas331,2026-01-29,0,25,(subject_fullname='efonseca_ef721_pas331' and ...
...,...,...,...,...,...
26,jyanar_ya067,2025-12-18,0,62,(subject_fullname='jyanar_ya067' and session_d...
27,jyanar_ya068,2025-12-18,0,62,(subject_fullname='jyanar_ya068' and session_d...
28,jyanar_ya069,2026-01-04,0,54,(subject_fullname='jyanar_ya069' and session_d...
29,jyanar_ya070,2026-01-04,0,55,(subject_fullname='jyanar_ya070' and session_d...
30,jyanar_ya071,2026-01-04,0,54,(subject_fullname='jyanar_ya071' and session_d...

In [136]:
sstable = acquisition.SessionStarted.proj(
    "local_path_behavior_file", "session_location"
)
stable = (acquisition.Session).proj(stimulusBank="stimulus_bank")
tstable = behavior.TowersSession.proj(
    trialType="rewarded_side", choice="chosen_side", stimulusSet="stimulus_set"
)
tbtable = behavior.TowersBlock.proj(
    "first_trial",
    "n_trials",
    "sublevel",
    mazeID="level",
    mainMazeID="main_level",
    easyBlockFlag="easy_block",
    duration="block_duration",
    rewardMil="reward_mil",
    medianTrialDur="trial_duration_median",
    start="block_start_time",
)
table_fetch = sstable * stable * tstable * tbtable

allblocks = pd.DataFrame(
    (table_fetch & block_query).fetch(
        order_by="subject_fullname, session_date desc, session_number desc, block desc",
        as_dict=True,
    )
)
allblocks["from_DB"] = 1
allblocks["session_date"] = allblocks["session_date"].astype(str)

allblocks["sublevel"] = allblocks["sublevel"].astype("Int64")
allblocks["choice"] = allblocks["choice"].apply(cast_choice)
allblocks["trialType"] = allblocks["trialType"].apply(cast_choice)

# allblocks['session_date'] = allblocks['session_date'].astype(str)
# allblocks['num_blocks'] = allblocks.groupby(['subject_fullname'])['subject_fullname'].rank(method='first')

# all_sessions_blocks = allblocks.drop_duplicates(subset=['subject_fullname','session_date','session_number']).copy()
# all_sessions_blocks['num_session_blocks'] = all_sessions_blocks.groupby(['subject_fullname'])['subject_fullname'].rank(method='first')
# all_sessions_blocks2 = all_sessions_blocks.copy()
# max_value_indices = all_sessions_blocks.groupby('subject_fullname')['num_session_blocks'].idxmax()
# all_sessions_blocks = all_sessions_blocks.loc[max_value_indices]

In [137]:
allblocks.to_csv(PAST_SESSION_PERFORMANCE_FILENAME, index=False)
allblocks

,subject_fullname,session_date,session_number,block,session_location,local_path_behavior_file,stimulusBank,stimulusSet,trialType,choice,...,mazeID,sublevel,n_trials,first_trial,duration,start,rewardMil,easyBlockFlag,medianTrialDur,from_DB
0,efonseca_ef505_act133,2026-03-04,0,1,165A-miniVR-T-3,C:\Data\efonseca\efonseca_ef505_act133\Session...,-- NO STIM BANK MODE --,1,"[1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1, ...","[2, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 2, 2, 2, ...",...,3,1,254,1,3600.040,2026-03-04 10:26:00,0.512,0,9.28662,1
1,efonseca_ef505_act133,2026-03-03,0,1,165A-miniVR-T-3,C:\Data\efonseca\efonseca_ef505_act133\Session...,-- NO STIM BANK MODE --,1,"[1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1, ...","[1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, ...",...,3,1,244,1,3600.030,2026-03-03 11:47:00,0.468,0,9.26066,1
2,efonseca_ef505_act133,2026-03-02,0,1,165A-miniVR-T-3,C:\Data\efonseca\efonseca_ef505_act133\Session...,-- NO STIM BANK MODE --,1,"[1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1, ...","[1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, ...",...,3,1,182,1,3600.030,2026-03-02 11:41:00,0.376,0,9.77846,1
3,efonseca_ef505_act133,2026-02-28,0,1,165A-miniVR-T-3,C:\Data\efonseca\efonseca_ef505_act133\Session...,-- NO STIM BANK MODE --,1,"[2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 1, ...","[2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, ...",...,3,1,83,1,3143.010,2026-02-28 12:06:00,0.196,0,9.74901,1
4,efonseca_ef505_act133,2026-02-27,0,3,165A-miniVR-T-3,C:\Data\efonseca\efonseca_ef505_act133\Session...,-- NO STIM BANK MODE --,1,"[1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 1, 1, ...","[1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, ...",...,2,3,293,38,2960.160,2026-02-27 10:20:00,1.168,0,6.07871,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3513,jyanar_ya071,2026-01-08,0,1,165I-Rig4-T,C:\Data\jyanar\jyanar_ya071\Session_jessejorge...,C:/Experiments/ViRMEn/experiments/protocols/st...,1,"[1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 2, ...","[1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 2, ...",...,1,<NA>,10,1,203.786,2026-01-08 10:52:00,0.080,0,13.52700,1
3514,jyanar_ya071,2026-01-07,0,1,165I-Rig4-T,C:\Data\jyanar\jyanar_ya071\Session_jessejorge...,C:/Experiments/ViRMEn/experiments/protocols/st...,1,"[1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 1]","[127, 127, 127, 127, 2, 2, 127, 127, 127, 2, 1...",...,1,<NA>,13,1,3762.830,2026-01-07 11:13:00,0.068,0,412.32000,1
3515,jyanar_ya071,2026-01-06,0,1,165I-Rig4-T,C:\Data\jyanar\jyanar_ya071\Session_jessejorge...,C:/Experiments/ViRMEn/experiments/protocols/st...,1,"[1, 1, 1, 2, 2, 2, 1, 2]","[127, 127, 127, 127, 127, 127, 127, 127]",...,1,<NA>,8,1,3301.600,2026-01-06 10:53:00,0.000,0,412.77700,1
3516,jyanar_ya071,2026-01-05,0,1,165I-Rig4-T,C:\Data\jyanar\jyanar_ya071\Session_jessejorge...,C:/Experiments/ViRMEn/experiments/protocols/st...,1,"[1, 1, 1, 2, 2, 2, 1, 2, 1, 2]","[1, 1, 1, 2, 2, 2, 1, 2, 1, 127]",...,1,<NA>,10,1,1893.440,2026-01-05 11:02:00,0.072,0,171.05800,1
3517,jyanar_ya071,2026-01-04,0,1,165I-Rig4-T,C:\Data\jyanar\jyanar_ya071\Session_jessejorge...,C:/Experiments/ViRMEn/experiments/protocols/st...,1,"[1, 1, 1, 2]","[1, 1, 127, 2]",...,1,<NA>,4,1,1224.820,2026-01-04 11:18:00,0.024,0,296.23200,1

In [138]:
subject_data = wwa.get_subject_data()
subject_data = subject_data.loc[
    :,
    [
        "user_id",
        "subject_fullname",
        "cage",
        "headplate_image_path",
        "last_weight",
        "water_per_day",
    ],
]
# subject_data = subject_data.loc[subject_data['user_id'] != 'testuser',:]
subject_data = subject_data.reset_index(drop=True)

dictionary_rename_cols = {
    "user_id": "owner",
    "subject_fullname": "subject name",
    "cage": "cage",
    "headplate_image_path": "headplate",
    "last_weight": "last weight",
    "water_per_day": "water per day",
}

subject_data = subject_data.rename(columns=dictionary_rename_cols)
subject_data = subject_data[list(dictionary_rename_cols.values())]
subject_data["headplate"] = subject_data["headplate"].astype(str)

headplate_image_paths = subject_data["headplate"].copy()

subject_data["last weight"] = subject_data["last weight"].round(1)
subject_data["water per day"] = subject_data["water per day"].round(1)


subject_data["headplate"] = ""
subject_data["today weight"] = ""
subject_data["today water"] = ""

In [139]:
# Copy the source file to the destination, replacing if it exists
shutil.copy2(
    WEIGHING_GUI_REPLACEMENT_SPREADHSHEET_FILENAME_TEMPLATE,
    WEIGHING_GUI_REPLACEMENT_SPREADHSHEET_FILENAME,
)

book = openpyxl.load_workbook(WEIGHING_GUI_REPLACEMENT_SPREADHSHEET_FILENAME)
sheet = book["Sheet1"]  # Replace 'Sheet1' with your sheet name

# sheet.delete_rows(3, sheet.max_row - 1) #

In [140]:
# for r in dataframe_to_rows(subject_data, index=False, header=False):
# sheet.append(r)

In [141]:
for r_idx, row in enumerate(
    dataframe_to_rows(subject_data, index=False, header=False), start=3
):
    for c_idx, value in enumerate(row, start=1):
        sheet.cell(row=r_idx, column=c_idx, value=value)

In [142]:
column_headplate = subject_data.columns.get_loc("headplate") + 1
column_headplate = openpyxl.utils.get_column_letter(column_headplate)


for i in range(headplate_image_paths.shape[0]):
    headplate_path = headplate_image_paths[i]
    cell_image = column_headplate + str(i + 3)

    if pathlib.Path.is_file(pathlib.Path(headplate_path)):
        img = Image(headplate_path)
        img.width = 60
        img.height = 60
        sheet.add_image(img, cell_image)
        sheet.row_dimensions[i + 3].height = 50
    else:
        sheet.row_dimensions[i + 3].height = 15

In [143]:
book.save(WEIGHING_GUI_REPLACEMENT_SPREADHSHEET_FILENAME)